name: sync-monk-coder-dust

on:
  schedule:
    - cron:  "*/30 * * * *"
  workflow_dispatch:
  watch:
    types: started

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: |
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

      - name: git clone monk-coder/dust
        run: |
          git clone https://github.com/monk-coder/dust dust

      - name: git push Aaron-lv/sync
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: dust
          github_token: ${{ secrets.PAT }}
          branch: dust
          force: true
